name: moffpass
version: 1.0.0+1
publish_to: none
description: Offline password manager
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  hive: 
  hive_flutter: 
  local_auth: 2.1.5
  flutter_secure_storage: ^8.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  build_runner: ^1.7.2
  flutter_launcher_icons: 0.12.0
  hive_generator: ^1.1.3
  logger: 1.1.0
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true  
  image_path: "assets/launcher/ic.png"
  adaptive_icon_background: 'assets/launcher/ic_launcher_background.png'
  adaptive_icon_foreground: 'assets/launcher/ic_launcher_foreground.png'

flutter: 
  uses-material-design: true
  assets:
    - assets/launcher/
    - assets/icons/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
